### ISSUE TITLE
Cài đặt BIOS

### ISSUE THREAD

**Issue by kakaphamno1** [motmaytinh/Dell-Inspiron-N3420-Hackintosh-OpenCore#1]
Bạn cho mình hỏi, có cần phải lưu ý hay cấu hình gì trong BIOS không ?

**Comment by motmaytinh** [comment]
Mình không nhớ rõ có phải cấu hình gì không. Bạn tham khảo thử cấu hình BIOS hiện tại của mình nhé:

- Virtualization: Enabled
- Integrated NIC: Enabled
- USB Emulation: Enabled
- USB Wake Support: Disabled
- SATA Operation: AHCI
- Secure Boot: Disabled *
- Boot List Option: UEFI
- Boot Option No.1: OpenCore

Nếu mình nhớ không lầm thì bắt buộc disable Secure Boot.

**Comment by kakaphamno1** [comment]
Thanks bạn nhé, để mình thử xem thế nào

**Comment by kakaphamno1** [comment]
Mình bị lỗi panic khắc phục thế nào vậy bạn
![IMG_20210530_234323](https://user-images.githubusercontent.com/22678022/120112737-3d767180-c1a1-11eb-9ffe-8502f68c767b.jpg)

**Comment by motmaytinh** [comment]
Rất tiếc mình không nhớ đã khắc phục lỗi panic này như thế nào và cũng không chắc là máy mình đã từng gặp lỗi như thế. Bạn chịu khó google vậy. Lỗi panic cũng có nhiều nguyên nhân nữa, nên mình nói trước là phải kiên nhẫn thử từng cách một nhé.
